#Database Project Physical Model 
#Group 14(E/17/219,E/17/027)

CREATE DATABASE HOSPITAL_MANAGEMENT_SYSTEM;

USE HOSPITAL_MANAGEMENT_SYSTEM;

CREATE TABLE PERSON(
	NID CHAR(10) NOT NULL PRIMARY KEY,
    FNAME VARCHAR(20) NOT NULL,
    LNAME VARCHAR(20) NOT NULL,
	SEX VARCHAR(6) NOT NULL,
	DOB DATE NOT NULL,
    ADRESSNO VARCHAR(10),
    STREET1 VARCHAR(20),
	STREET2 VARCHAR(20),
    CITY VARCHAR(20) NOT NULL,
    PHONENUMBER CHAR(10),
    CIVILSTATUS VARCHAR(10) NOT NULL,
    PERSONTYPE VARCHAR(8) NOT NULL
);

CREATE TABLE DEPENDENT(
    DNAME VARCHAR(50) NOT NULL,
	SEX VARCHAR(6) NOT NULL,
	DOB DATE NOT NULL,
	RELATIONSHIP VARCHAR(10) NOT NULL,
    PERSONID CHAR(10),
    PRIMARY KEY (DNAME,PERSONID),
	FOREIGN KEY (PERSONID) REFERENCES PERSON (NID)
    
);


CREATE TABLE DOCTOR(

	NID CHAR(10) NOT NULL PRIMARY KEY,
    SPECIALIZATION VARCHAR(40)

);


CREATE TABLE SECTION(

	SNAME VARCHAR(20) NOT NULL PRIMARY KEY,
	PHONE CHAR(10),
    BUILDIGNO INT NOT NULL,
    DIRECTORID CHAR(10) NOT NULL,
    DIRSTARTDATE DATE,
    FOREIGN KEY (DIRECTORID) REFERENCES DOCTOR(NID)
);


CREATE TABLE H_RESOURCE(

	RNAME VARCHAR(50) NOT NULL PRIMARY KEY,
    MANUFACTURER VARCHAR(20),
	NOOFUNITS INT NOT NULL,
	SECTIONNAME VARCHAR(20) NOT NULL,
	IMPORTEDDATE DATE,
	FOREIGN KEY (SECTIONNAME) REFERENCES SECTION(SNAME)
    
);


CREATE TABLE MEDICALREPORT(

	REPORTNO INT NOT NULL PRIMARY KEY,
	ISSUEDATE DATE NOT NULL, 
	TEST VARCHAR(20) NOT NULL,
    LAB VARCHAR(20) NOT NULL

);

CREATE TABLE MEDICINE(

	SCIENTIFICNAME VARCHAR(50) NOT NULL PRIMARY KEY,
    MANUFACTURER VARCHAR(20) NOT NULL,
    NOOFUNITS INT NOT NULL,
    COMMERCIALNAME VARCHAR(20),
    PHYSICALSTATE VARCHAR(10),
    UNITPRICE DECIMAL(5,2) NOT NULL
    
);

CREATE TABLE PATIENT(

	NID CHAR(10) NOT NULL PRIMARY KEY,
    BGROUP VARCHAR(3),
    PATIONNO INT NOT NULL

);

CREATE TABLE PATIENTALLERGY(

	PATIENTNID CHAR(10) NOT NULL,
    ALLERGY VARCHAR(20) NOT NULL,
    PRIMARY KEY (PATIENTNID, ALLERGY),
    FOREIGN KEY (PATIENTNID) REFERENCES DOCTOR(NID)

);

CREATE TABLE EMPLOYEE(

	NID CHAR(10) NOT NULL PRIMARY KEY,
    ESTATUS VARCHAR(20) NOT NULL,
    ENUMBER INT NOT NULL,
    SECTIONNAME VARCHAR(20) NOT NULL,
	WORKHOURS INT NOT NULL,
    OTHOURS INT NOT NULL,
	FOREIGN KEY ( SECTIONNAME) REFERENCES SECTION(SNAME)
);

CREATE TABLE WARD(

	WARDNO INT NOT NULL PRIMARY KEY,
    WNAME VARCHAR(30),
    NOOFEMPLOYEES INT NOT NULL,
	NOOFBEDS INT NOT NULL,
	AVAILABLEBEDS INT NOT NULL,
	MANAGERID CHAR(10) NOT NULL,
	MGRSTARTDATE DATE NOT NULL,
    DOCTORID CHAR(10) NOT NULL,
    DOCSTARTDATE DATE NOT NULL,
    FOREIGN KEY (MANAGERID) REFERENCES EMPLOYEE(NID),
    FOREIGN KEY (DOCTORID) REFERENCES EMPLOYEE(NID)
);

CREATE TABLE WARDBUILDINGNO(

	WARDNO INT NOT NULL,
	BUILDINGNO INT NOT NULL,
	PRIMARY KEY(WARDNO,BUILDINGNO),
	FOREIGN KEY (WARDNO) REFERENCES WARD(WARDNO)
);

CREATE TABLE CONSUMEDIN(

	SECTIONNAME VARCHAR(20) NOT NULL,
    MEDSCIENTIFICNAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (SECTIONNAME,MEDSCIENTIFICNAME),
    FOREIGN KEY (SECTIONNAME) REFERENCES SECTION(SNAME),
	FOREIGN KEY (MEDSCIENTIFICNAME) REFERENCES MEDICINE(SCIENTIFICNAME)
);

CREATE TABLE TREATSIN(

	SECTIONNAME VARCHAR(20) NOT NULL,
    DOCTORNID CHAR(10) NOT NULL,
    WORKHOURS INT NOT NULL,
    OTHOURS INT NOT NULL,
    PRIMARY KEY (SECTIONNAME,DOCTORNID),
    FOREIGN KEY (SECTIONNAME) REFERENCES SECTION(SNAME),
	FOREIGN KEY (DOCTORNID) REFERENCES DOCTOR(NID)
);

CREATE TABLE TREATSON(

	PATIENTNID CHAR(10) NOT NULL,
    DOCTORNID CHAR(10) NOT NULL,
    TREATDATE DATE NOT NULL,
    ILLNESS VARCHAR(20) NOT NULL,
    PRIMARY KEY (PATIENTNID,DOCTORNID),
    FOREIGN KEY (PATIENTNID) REFERENCES PATIENT(NID),
	FOREIGN KEY (DOCTORNID) REFERENCES DOCTOR(NID)
);

CREATE TABLE REGISTERED(

	PATIENTNID CHAR(10) NOT NULL,
	WARDNO INT NOT NULL ,
    REGISTEREDDATE DATE NOT NULL,
    ILLNESS VARCHAR(20) NOT NULL,
    PRIMARY KEY (PATIENTNID,WARDNO),
    FOREIGN KEY (PATIENTNID) REFERENCES PATIENT(NID),
	FOREIGN KEY (WARDNO) REFERENCES WARD(WARDNO)
);

CREATE TABLE ISSUES(

	PATIENTNID CHAR(10) NOT NULL,
    DOCTORNID CHAR(10) NOT NULL,
    REPORTNO INT NOT NULL,
    PRIMARY KEY (PATIENTNID,DOCTORNID,REPORTNO),
    FOREIGN KEY (PATIENTNID) REFERENCES PATIENT(NID),
	FOREIGN KEY (DOCTORNID) REFERENCES DOCTOR(NID),
    FOREIGN KEY (REPORTNO) REFERENCES MEDICALREPORT(REPORTNO)
);



